#!/usr/bin/env python3
"""power_sequencing.py - does every negative rail follow the positive rail it must follow?

Issue #20 asked whether the three converters whose EN is tied to VIN (U3 -> +3V3, U11 -> +3V4,
U12 -> +5V0_0) break the power-up order.  The answer is that they do not, for a structural reason
worth locking down:

    every negative rail on this board is generated by an LM2662 charge pump, and a charge pump has
    no enable pin - it runs whenever its V+ is present.  So a negative rail cannot possibly come up
    before the positive rail feeding it.

That makes the order self-enforcing rather than dependent on sequencing logic, and it satisfies the
ADTR1107's recommended sequence, which the datasheet states explicitly:

    transmit power-up:  1. GND  2. VDD_SW = 3.3 V  3. VSS_SW = -3.3 V  ...  8. VDD_PA = 5 V
                        9. VGG_PA to IDQ  10. RF

- the positive switch rail first, then the negative.  The same pattern holds on every rail pair here.

This gate checks the property that makes that true: each negative rail's pump draws from a positive
rail of the same family.  If a re-spin ever re-sources a pump from a rail that comes up later, the
pairing breaks and this fails.

Exit status is 0 when the pairing holds.
"""
import re
import sys
from pathlib import Path

PUMP = "LM2662MX/NOPB"


def nets_of(text):
    """All nets as a LIST of (name, body) pairs.

    Not a dict: net names repeat across sheets in Eagle, and a dict silently keeps only the last
    one - which is exactly how a fault injection once looked like a clean pass.
    """
    return [(m.group(1), m.group(2))
            for m in re.finditer(r'<net name="([^"]+)"[^>]*>(.*?)</net>', text, re.S)]


def pins_on(nets, ref):
    out = []
    for name, body in nets:
        for part, pin in re.findall(r'part="([^"]+)"[^>]*pin="([^"]+)"', body):
            if part == ref:
                out.append((name, pin))
    return out


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    sch = root / "4_Schematics and Boards Layout/4_6_Schematics/PowerBoard/PowerBoard.sch"
    if not sch.exists():
        print(f"  [skip] {sch} not present")
        return 0
    text = sch.read_text(encoding="utf-8", errors="replace")
    nets = nets_of(text)

    # every part, and which deviceset it is
    parts = {m.group(1): m.group(2) for m in re.finditer(r'<part name="([^"]+)"([^>]*)/>', text)}
    pumps = [r for r, a in parts.items() if PUMP in a]
    print(f"  {len(pumps)} charge-pump inverter(s): {', '.join(sorted(pumps, key=lambda x: int(x[1:])))}")

    findings = []
    pairs = []
    for ref in sorted(pumps, key=lambda x: int(x[1:])):
        taps = pins_on(nets, ref)
        vplus = [n for n, p in taps if p.upper() in ("V+", "VIN", "VCC", "IN")]
        vout = [n for n, p in taps if p.upper() in ("OUT", "VOUT", "VO")]
        if not vout:
            continue
        neg = vout[0]
        if not vplus:
            findings.append(f"{ref} produces {neg} but nothing feeds its V+")
            continue
        src = vplus[0]
        pairs.append((ref, neg, src))
        # the pairing rule: the source must be a positive rail of the same family
        if not src.startswith("+"):
            findings.append(f"{ref}: {neg} is fed from {src}, which is not a positive rail")
        else:
            # -3V3_SW <- +3V3_SW, -5V0_ADAR <- +5V0_ADAR, -3V4 <- +3V4, -5V5_PA <- +5V5_PA
            if neg.lstrip("-").split("_")[0] != src.lstrip("+").split("_")[0]:
                findings.append(f"{ref}: {neg} is fed from {src} - different rail family, so the "
                                f"negative could precede the positive it belongs to")
    print("\n  pump            negative rail     fed from")
    for ref, neg, src in pairs:
        print(f"  {ref:6}          {neg:16}  {src}")

    # which converters are staged, and which are not - the second half of the question
    unstaged = []
    for ref, attrs in sorted(parts.items(), key=lambda kv: int(kv[0][1:]) if kv[0][1:].isdigit() else 0):
        if "TPS562208" not in attrs and "ADM7151" not in attrs and "TPS7A8300" not in attrs:
            continue
        taps = pins_on(nets, ref)
        en = [n for n, p in taps if p.upper() == "EN"]
        vin = [n for n, p in taps if p.upper() in ("VIN", "VIN,EN")]
        if en and vin and en[0] == vin[0]:
            unstaged.append(f"{ref} ({en[0]})")
    print(f"\n  unstaged converters (EN tied to their input): {len(unstaged)}")
    for u in unstaged:
        print(f"    {u}")
    print("    ^ each of these is a *positive* rail, and every negative rail is a charge pump fed")
    print("      from a positive one, so the negative can never precede its positive.")

    print()
    if findings:
        print("FINDINGS")
        for f in findings:
            print("  - " + f)
        return 1
    print("every negative rail follows a positive rail of its own family.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
