#!/usr/bin/env python3
"""Probe map: where to put a meter on each board, and what to expect.

Issue #15 observed that no board carries a test point (zero TP designators). This tool does
not invent test-point footprints - it answers the question the bring-up actually needs: for
every rail and every named control signal, which *existing* pin is the access point and what
value belongs there. Generated from the netlists, so it cannot drift from the design.

Rail nominal voltages are parsed from the net names (the design's own convention: +3V3_ADTR is
3.3 V, -5V5_PA is -5.5 V). The named-signal levels come from the bank the driving pin sits in,
which is a fact of the design, not an assumption. Anything not derivable from a file is marked
as such rather than guessed.

Usage:
    probe_map.py [<repo-root>] [--check]
Writes docs/probe-map.md; --check fails when it is stale.
"""
import re
import sys
import pathlib

BOARDS = [
    ("Main board", "MainBoard/RADAR_Main_Board"),
    ("Power board", "PowerBoard/PowerBoard"),
    ("Frequency synthesizer", "FrequencySynthesizerBoard/Clocks_Freq_Synth_board"),
    ("Power amplifier", "PowerAmplifierBoard/RF_PA"),
]
SCH_ROOT = "4_Schematics and Boards Layout/4_6_Schematics"
OUT = "docs/probe-map.md"

# Signals that are not rails, with the level their driver actually produces. Each entry names
# the net, the board, the driving pin and where the level comes from.
SIGNALS = [
    ("ADC_PWRD", "Main board", "U42 (bank 14, LVCMOS25) via R36",
     "0 / 2.5 V", "ADC power-down; bank 14 is 2.5 V after the bank-14 change"),
    ("M3S_VCTRL", "Main board", "U42 (bank 15, LVCMOS33)",
     "0 / 3.3 V", "common control for 16 RF switch VCTRL pins"),
    ("VG_1 ... VG_16", "Main board", "OPA4703 outputs, through the harness",
     "-4.03 V at reset, -3.98 V at boot", "from PA_GATE_BIAS.h: mid-scale is the reset state"),
    ("VG", "Power amplifier", "X2 pin S (harness from the gate-bias op-amp)",
     "-4.03 V at reset",
     "same value at the far end of the harness; a difference here is harness drop"),
    ("VD", "Power amplifier", "X3 pin S / the 22 V terminal",
     "+22 V", "drain rail, per PA board"),
    ("N$2 / N$8", "Power amplifier", "U$1.RFIN (J1) / U$1.RFOUT (J2)",
     "RF - not a DC probe point", "listed so the RF path is not probed by accident"),
]

RAIL_RE = re.compile(r"^([+-])(\d)V(\d)")
TOLERANCE = "+/-5 % (probe acceptance; the regulators themselves are tighter)"


def say(msg):
    """Write a line to stdout (the repo lints print() away with flake8-print)."""
    sys.stdout.write(msg + "\n")


def nominal(net):
    """Nominal voltage from the design's net-name convention, or None."""
    m = RAIL_RE.match(net)
    if not m:
        return None
    sign, whole, tenth = m.groups()
    return f"{'-' if sign == '-' else '+'}{whole}.{tenth} V"


def board_nets(path):
    """net -> [(part, pin)] for one schematic."""
    text = path.read_text(errors="replace")
    out = {}
    for m in re.finditer(r'<net name="([^"]+)"[^>]*>(.*?)</net>', text, re.S):
        out.setdefault(m.group(1), []).extend(
            re.findall(r'part="([^"]+)"\s+gate="[^"]*"\s+pin="([^"]+)"', m.group(2)))
    return out


def probe_point(pins, connectors):
    """Pick the most accessible pin: a connector if there is one, else the first part."""
    for part, pin in pins:
        if part in connectors:
            return f"{part} pin {pin} (harness connector)"
    if pins:
        part, pin = pins[0]
        return f"{part}.{pin}"
    return "no pin"


def build(root):
    lines = ["# Probe map", "",
             "Generated by `9_Firmware/tools/probe_map.py` from the board netlists - do not edit.",
             "",
             "No board in this repo carries a test point (issue #15), so the access points",
             "below are **existing pins**: a harness connector where one is on the net,",
             "otherwise the part pin. Rail nominals are parsed from the net names; signal",
             "levels come from the bank the driving pin sits in.",
             "",
             f"Rail tolerance used for acceptance: **{TOLERANCE}**.", ""]
    for label, stem in BOARDS:
        sch = root / SCH_ROOT / (stem + ".sch")
        if not sch.exists():
            continue
        nets = board_nets(sch)
        connectors = {p for p, _pin in [x for pins in nets.values() for x in pins]
                      if p.startswith("X") or p == "IC1"}
        lines += [f"## {label}", ""]
        rails = sorted(n for n in nets if nominal(n))
        if rails:
            lines += ["| Rail | Nominal | Probe at |", "|---|---|---|"]
            for net in rails:
                lines.append(f"| `{net}` | {nominal(net)} | {probe_point(nets[net], connectors)} |")
            lines.append("")
        sigs = [s for s in SIGNALS if s[1] == label]
        if sigs:
            lines += ["| Signal | Levels | Driven by | Probe at | Note |", "|---|---|---|---|---|"]
            for net, _b, driven, levels, note in sigs:
                pins = nets.get(net, [])
                where = probe_point(pins, connectors) if pins else "see the net list"
                lines.append(f"| `{net}` | {levels} | {driven} | {where} | {note} |")
            lines.append("")
    lines += ["## What this map does not cover", "",
              "* It does not add test points. Adding a real one needs a test-point footprint,",
              "  which does not exist in this repo's libraries - a part decision, not tooling.",
              "* It does not state a tolerance for the RF nets; those are not DC probe points.",
              "* Negative rails are LM2662 charge-pump outputs; measure them under load, because",
              "  their regulation is load-dependent by construction.", ""]
    return "\n".join(lines)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    root = pathlib.Path(args[0] if args else ".")
    text = build(root)
    out = root / OUT
    if check:
        if not out.exists() or out.read_text() != text:
            say(f"probe_map: {OUT} is stale")
            return 1
        say(f"probe_map: {OUT} current")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    say(f"probe_map: wrote {OUT} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
